version: '3.7'

volumes:
  data-db:
services:
  web:
    build: ./bookmybook
    image: bookmybook
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./bookmybook/:/usr/src/bookmybook/
    expose:
      - 8000
    links:
      - mongodb
    # depends_on:
    #   - migration
    env_file:
      - ./.env.dev

  mongodb:
    image: mongo
    restart: always
    volumes:
      - ./data-db:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: osmentos
      MONGO_INITDB_DATABASE: books
    ports:
      - 27017:27017

  # migration:
  #   build: .
  #   image: bookmybook
  #   command: python manage.py migrate
  #   volumes:
  #     - ./bookmybook/:/usr/src/bookmybook/
  #   links:
  #     - mongodb
  #   depends_on:
  #     - make_migrations

  # make_migrations:
  #   build: .
  #   image: bookmybook
  #   command: python manage.py makemigrations
  #   volumes:
  #     - ./bookmybook/:/usr/src/bookmybook/
  #   links:
  #     - mongodb
  #   depends_on:
  #     - mongodb

  nginx:
    build: ./nginx
    ports:
      - 1337:80
    depends_on:
      - web



