version: '3.7'

volumes:
    mysql:
    bookmybook:
    sql:  



services:

  db:
    command: mysqld
    image: mysql:5.7
    ports:
      - '3306:3306'
    environment:
       MYSQL_DATABASE: 'books'
       MYSQL_USER: 'root'
       MYSQL_PASSWORD: 'osmentos'
       MYSQL_ROOT_PASSWORD: 'osmentos'
    volumes:
      - ./mysql:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d
  web:
    build: ./bookmybook
    image: bookmybook
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./bookmybook/:/usr/src/bookmybook/
      - ./mysql:/var/lib/mysql
    expose:
      - 8000
    depends_on:
      - db
    env_file:
      - ./.env.dev
  
  nginx:
    build: ./nginx
    ports:
      - 80:80
    depends_on:
      - web



