version: '3.7'

volumes:
    mysql:
    bookmybook:
    sql:  
    zookeeper_data:
    kafka_data:

services:

  db:
    command: mysqld
    image: mysql:5.7
    ports:
      - '3306:3306'
    environment:
       MYSQL_DATABASE: 'userauth1'
       MYSQL_USER: 'root'
       MYSQL_PASSWORD: 'osmentos'
       MYSQL_ROOT_PASSWORD: 'osmentos'
    volumes:
      - ./mysql:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d

  web:
    build: ./bookmybook
    image: bookmybook
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./bookmybook/:/usr/src/bookmybook/
      - ./mysql:/var/lib/mysql
    expose:
      - 8000
    depends_on:
      - db
    env_file:
      - ./.env.dev
  
  nginx:
    build: ./nginx
    ports:
      - 80:80
    depends_on:
      - web

  redis:
    image: redis:latest
    ports:
        - 6379:6379
    volumes:
        - ./redis.conf:/redis.conf
    command: [ "redis-server", "/redis.conf" ]

  zookeeper:
    image: 'docker.io/bitnami/zookeeper:3-debian-10'
    ports:
      - '2181:2181'
    volumes:
      - 'zookeeper_data:/bitnami'
    environment:
    - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: 'docker.io/bitnami/kafka:2-debian-10'
    ports:
      - '9092:9092'
    volumes:
      - 'kafka_data:/bitnami'
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper



